# Generated by Django 3.1.5 on 2021-01-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data',
            new_name='keyword_info',
        ),
    ]
