# Generated by Django 3.1.5 on 2021-01-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0002_auto_20210129_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword_info',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
