# Generated by Django 3.1.5 on 2021-01-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0003_auto_20210129_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword_info',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
