# Generated by Django 3.1.5 on 2021-01-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0004_auto_20210130_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='buisness_leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
            ],
        ),
    ]
